### ISSUE TITLE
clair restarts repeatedly when there is some issue with vulnerability repos

### ISSUE THREAD

**Issue by n-guitar** [bitnami/bitnami-docker-harbor-clair#1]
**Description**
The same thing will happen as below.
https://github.com/goharbor/harbor/issues/14720

It has been reported that this is a bug in clair.
And this bug has been fixed in clair.
https://github.com/quay/clair/commit/31e704b589553981c47cdaa0c519d4f909fa7db6

When will this fix be incorporated?

**Steps to reproduce the issue:**

1. [First Step]
There was an issue with a vulnerability repo: https://git.launchpad.net/ubuntu-cve-tracker/
2. [Second Step]
Crash pod
```
{"Event":"could not pull ubuntu-cve-tracker repository","Level":"error","Location":"ubuntu.go:174","Time":"2021-06-09 17:12:07.113388","error":"exit status 128","output":"Cloning into '.'...\nfatal: unable to access 'https://git.launchpad.net/ubuntu-cve-tracker/': The requested URL returned error: 503\n"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-06-09 17:12:07.113433","error":"could not download requested resource","updater name":"ubuntu"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2021-06-09 17:12:07.802268","updater name":"amzn1"}
{"Event":"Failed to update RHEL","Level":"error","Location":"rhel.go:140","StatusCode":403,"Time":"2021-06-09 17:12:08.217779"}
{"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:246","Time":"2021-06-09 17:12:08.217903","error":"could not download requested resource","updater name":"rhel"}
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:279","Time":"2021-06-09 17:12:08.217930"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2021-06-09 17:12:09.931884","data feed name":"2002","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.meta failed status code: 404"}
```

**Version**

- Output of `docker version`:

```
docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 31
  Running: 18
  Paused: 0
  Stopped: 13
 Images: 14
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-514.16.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.797GiB
 Name: devk8sms201apf
 ID: HCFI:RF54:VA3L:GU73:XL72:KKQM:OCAK:JF75:FLR3:JVHV:74LV:SGW4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):
not use.

- Output of `kubectl describe deployments.apps -n harbor harbor-clair `

```
kubectl describe deployments.apps -n harbor harbor-clair 
Name:                   harbor-clair
Namespace:              harbor
CreationTimestamp:      Thu, 13 May 2021 12:12:51 +0000
Labels:                 app.kubernetes.io/component=clair
                        app.kubernetes.io/instance=harbor
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=harbor
                        helm.sh/chart=harbor-10.0.2
                        io.cattle.field/appId=harbor
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: harbor
                        meta.helm.sh/release-namespace: harbor
Selector:               app.kubernetes.io/component=clair,app.kubernetes.io/instance=harbor,app.kubernetes.io/name=harbor,io.cattle.field/appId=harbor
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app.kubernetes.io/component=clair
                app.kubernetes.io/instance=harbor
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=harbor
                helm.sh/chart=harbor-10.0.2
                io.cattle.field/appId=harbor
  Annotations:  checksum/secret: xxxx
  Containers:
   clair:
    Image:      docker.io/bitnami/harbor-clair:2.2.1-debian-10-r26
    Port:       6060/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:6061/health delay=20s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:6061/health delay=20s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:  false
      NO_PROXY:       harbor-core,harbor-jobservice,harbor-database,harbor-chartmuseum,harbor-clair,harbor-notary-server,harbor-notary-signer,harbor-registry,harbor-portal,harbor-trivy,127.0.0.1,localhost,.local,.internal
    Mounts:
      /etc/clair/config.yaml from config (rw,path="config.yaml")
   adapter:
    Image:      docker.io/bitnami/harbor-adapter-clair:2.2.1-debian-10-r26
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/probe/healthy delay=20s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:8080/probe/ready delay=20s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:               false
      SCANNER_CLAIR_URL:           http://127.0.0.1:6060
      SCANNER_STORE_REDIS_URL:     redis://harbor-redis-master:6379/4
      SCANNER_CLAIR_DATABASE_URL:  <set to the key 'database' in secret 'harbor-clair'>  Optional: false
    Mounts:                        <none>
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor-clair
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   harbor-clair-89df59799 (1/1 replicas created)
Events:          <none>
```

- Other details that may be helpful:

info| |
-- | --
Architecture | amd64
Boot ID | 441ead8d-9d88-429f-8d58-6d7d2dba8ea5
Container Runtime Version | docker://20.10.5
Image | Red Hat Enterprise Linux Server 7.3 (Maipo)
Kernel Version | 3.10.0-514.16.1.el7.x86_64
Kube Proxy Version | v1.20.5
Kubelet Version | v1.20.5
Machine ID | —
Operating System | linux
System UUID | 4232EC85-A7AA-E0D3-37DC-AB0A2ABCBFE8

**Comment by marcosbc** [comment]
Hi @n-guitar, once a new version of Clair is released (i.e. 4.1.1 or 4.2.0), our CI will automatically detect it and proceed with the release. Unfortunately it does not seem like a new version was released yet, so we'll have to wait.

**Comment by marcosbc** [comment]
Actually please ignore my above comment. I just noticed that we are using a different branch (version 2). Also, this seems to be already fixed in 2.1.7. I'm looking into what has happened since it was released a couple of months ago.

**Comment by marcosbc** [comment]
Hi, it seems like we were not tracking the latest version properly. I've started the release process of the new version, so if everything goes fine it should be out before the end of the weekend.

**Comment by n-guitar** [comment]
Hi @marcosbc , Thanks for the good news!
I will wait for it to be released.

**Comment by marcosbc** [comment]
Hi @n-guitar, this should have been fixed in [`bitnami/harbor-clair:2.2.2-debian-10-r18`](https://github.com/bitnami/bitnami-docker-harbor-clair/commit/33304c014a467957e5888605e25bd91ee59d1a02) which includes Clair 2.1.7.

**Comment by ahlae** [comment]
This is still happening to me. I'm running:

docker.io/bitnami/harbor-clair:2.3.0-debian-10-r8

from the latest bitnami helm chart harbor-10.2.2.

The clair pod restarts every time it fetches updates:

 10:13:44.42 
 10:13:44.42 Welcome to the Bitnami harbor-clair container
 10:13:44.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-harbor-clair
 10:13:44.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-harbor-clair/issues
 10:13:44.44 
 10:13:44.44 INFO  ==> ** Starting Harbor Clair setup **
 10:13:44.46 INFO  ==> Validating Harbor Clair settings...
 10:13:44.47 INFO  ==> No custom certificates were installed in the system
 10:13:44.47 INFO  ==> Waiting for PostgreSQL to be available at harbor-postgresql:5432...
 10:13:44.51 INFO  ==> ** Harbor Clair setup finished! **

 10:13:44.52 INFO  ==> ** Starting Harbor Clair **
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2021-07-22 10:13:44.570604"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:223","Time":"2021-07-22 10:13:44.595892"}
{"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2021-07-22 10:13:44.596371","port":6061}
{"Event":"updater service started","Level":"info","Location":"updater.go:83","Time":"2021-07-22 10:13:44.596450","lock identifier":"e39c0a32-0e60-45a6-97e2-ef3a4d51eabe"}
{"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:77","Time":"2021-07-22 10:13:44.597098"}
{"Event":"starting main API","Level":"info","Location":"api.go:52","Time":"2021-07-22 10:13:44.597210","port":6060}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2021-07-22 10:20:51.730505"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2021-07-22 10:20:51.730667"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2021-07-22 10:20:51.730995","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2021-07-22 10:20:51.731735","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2021-07-22 10:20:51.754804","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2021-07-22 10:20:51.755118","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2021-07-22 10:20:51.755592","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2021-07-22 10:20:51.756039","package":"Amazon Linux 2"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2021-07-22 10:20:51.801207","package":"Amazon Linux 2018.03"}
panic: runtime error: slice bounds out of range [25:24]

goroutine 315 [running]:
github.com/coreos/clair/ext/vulnsrc/rhel.toFeatureVersions(0xc00009a590, 0x2, 0xc000130078, 0x1, 0x1, 0xc0002820d0, 0x1, 0x1, 0x203000, 0x203000, ...)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:292 +0xc46
github.com/coreos/clair/ext/vulnsrc/rhel.parseRHSA(0x7f6418078ac0, 0xc0001f21e0, 0xc0001f21e0, 0x7f6418078ac0, 0xc0001f21e0, 0x8ea73a, 0x4)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:182 +0x1eb
github.com/coreos/clair/ext/vulnsrc/rhel.(*updater).Update(0xc099c8, 0x98e6a0, 0xc000070c40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:145 +0x6c5
github.com/coreos/clair.fetch.func1(0x98e6a0, 0xc000070c40, 0xc00012eb88, 0xc000101080, 0x8ea9ee, 0x4, 0x982760, 0xc099c8)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:243 +0xa8
created by github.com/coreos/clair.fetch
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:242 +0x1b0

**Comment by carrodher** [comment]
It seems a totally different issue, in order to avoid mixing topics, can you please create a new issue providing the information requested by the automated template? It's easy for us in order to try to reproduce your issue. Thanks

**Comment by ahlae** [comment]
Sorry for that. Your right, I accidentally mixed up issues and put this in here. I'll brought this over here: [https://github.com/bitnami/bitnami-docker-harbor-clair/issues/2](url)

**Comment by carrodher** [comment]
Thanks! Our team is actively monitoring the GH issues and will provide an answer during the next business day
